import L from "leaflet";

// Static GeoJSON generated by scripts/refresh-keuskupan.py — 514 kabupaten
// polygons, each tagged with the diocese it belongs to plus that diocese's
// metadata (bishop, founding date, cathedral, ecclesiastical province).
function keuskupanUrl() {
  return `${import.meta.env.BASE_URL}keuskupan/keuskupan.geojson`;
}

export const KEUSKUPAN_SOURCES = [
  { key: "keuskupan_katolik", label: "Keuskupan Katolik", group: "Gereja Katolik",
    kind: "keuskupan", url: keuskupanUrl() },
];

// One hue per ecclesiastical province (10 total). Picked from ColorBrewer
// Set3/Paired so neighbouring provinces stay distinguishable and the whole
// palette works in both light and dark map basemaps.
const PROVG_COLOR = {
  "Medan":     "#e41a1c",  // red        — Sumatera utara
  "Palembang": "#ff7f00",  // orange     — Sumatera selatan/tengah
  "Jakarta":   "#ffd92f",  // yellow     — Jabodetabek + Jabar barat/tengah
  "Semarang":  "#4daf4a",  // green      — Jateng, DIY, Jatim
  "Ende":      "#66c2a5",  // teal       — Flores, Bali, NTB
  "Kupang":    "#00c8d7",  // cyan       — Timor + Sumba
  "Pontianak": "#377eb8",  // blue       — Kalbar
  "Samarinda": "#7570b3",  // indigo     — Kalteng, Kalsel, Kaltim, Kaltara
  "Makassar":  "#984ea3",  // purple     — Sulawesi + Maluku
  "Merauke":   "#f781bf",  // pink       — Papua
};

export const KEUSKUPAN_PROVG_COLOR = PROVG_COLOR;

function colorFor(provg) {
  return PROVG_COLOR[provg] || "#999";
}

const BASE_STYLE = {
  weight: 0.5,
  color: "#ffffff",
  opacity: 0.75,
  fillOpacity: 0.65,
};
const HOVER_STYLE = {
  weight: 2,
  color: "#1a1614",
  opacity: 1,
  fillOpacity: 0.8,
};

const escapeHtml = (s) => {
  const div = document.createElement("div");
  div.textContent = String(s ?? "");
  return div.innerHTML;
};

function statusLabel(p) {
  if (p.status === "Metropolit") return "Keuskupan Agung · Metropolit";
  if (p.status === "Sufragan")   return `Sufragan · Prov. Gerejawi ${p.provg}`;
  return p.status;
}

function popupHtml(p) {
  const uskup = p.uskup === "Lowong"
    ? `<em style="color:#b30000">Lowong</em> <span style="opacity:.7">(sejak ${escapeHtml(p.usejak)})</span>`
    : `${escapeHtml(p.uskup)} <span style="opacity:.7">(sejak ${escapeHtml(p.usejak)})</span>`;

  const swatch = `<span style="display:inline-block;width:10px;height:10px;border-radius:2px;
    background:${colorFor(p.provg)};margin-right:6px;vertical-align:middle"></span>`;

  const rows = [
    ["Kabupaten/Kota", escapeHtml(p.kab)],
    ["Provinsi",       escapeHtml(p.prov)],
    ["Keuskupan",      `<strong>${escapeHtml(p.keuskupan)}</strong>`],
    ["Status",         `${swatch}${escapeHtml(statusLabel(p))}`],
    ["Berdiri",        escapeHtml(p.berdiri)],
    ["Uskup",          uskup],
    ["Katedral",       escapeHtml(p.katedral)],
  ];
  const rowsHtml = rows.map(([k, v]) =>
    `<div><strong>${k}:</strong> ${v}</div>`,
  ).join("");
  return `<div style="font-size:12px;line-height:1.5;max-width:320px">${rowsHtml}</div>`;
}

function tooltipHtml(p) {
  return `<strong>${escapeHtml(p.keuskupan)}</strong>
    <span style="opacity:.75">— ${escapeHtml(p.kab)}</span>`;
}

function styleFor(feature) {
  return { ...BASE_STYLE, fillColor: colorFor(feature.properties.provg) };
}

async function buildKeuskupan(_key, url) {
  const r = await fetch(url, { cache: "no-store" });
  if (!r.ok) throw new Error(`HTTP ${r.status} for keuskupan GeoJSON`);
  const fc = await r.json();

  const layer = L.geoJSON(fc, {
    style: styleFor,
    onEachFeature: (feature, sub) => {
      const p = feature.properties;
      sub.bindTooltip(tooltipHtml(p), { sticky: true, direction: "top", opacity: 0.95 });
      sub.bindPopup(popupHtml(p), { maxWidth: 360 });
      sub.on({
        mouseover: (e) => e.target.setStyle(HOVER_STYLE),
        mouseout:  (e) => layer.resetStyle(e.target),
      });
    },
  });
  layer._meta = {
    keuskupan: fc.keuskupan_count,
    provg:     fc.provinsi_gerejawi_count,
    kabupaten: fc.kabupaten_covered,
  };
  return layer;
}

export const KEUSKUPAN_BUILDERS = new Map([["keuskupan", buildKeuskupan]]);
