import L from "leaflet";

// Static JSON generated by scripts/build_mbg_incidents.py from the Wikipedia
// table + kabkota centroids. Lives under public/ so it deploys with the app.
function mbgUrl() {
  return `${import.meta.env.BASE_URL}mbg/incidents.json`;
}

export const MBG_SOURCES = [
  { key: "mbg_keracunan", label: "Keracunan MBG", group: "Insiden · MBG",
    kind: "mbg", url: mbgUrl() },
];

// Warm ramp: lightest = few victims, darkest = many. Buckets chosen so the
// long tail (a handful of >500-victim incidents) reads distinctly.
const RAMP = [
  { max: 10,       color: "#fee08b", label: "≤ 10" },
  { max: 50,       color: "#fdae61", label: "11–50" },
  { max: 150,      color: "#f46d43", label: "51–150" },
  { max: 400,      color: "#d73027", label: "151–400" },
  { max: 800,      color: "#a50026", label: "401–800" },
  { max: Infinity, color: "#67001f", label: "> 800" },
];

export const MBG_RAMP = RAMP;

function colorFor(n) {
  for (const r of RAMP) if (n <= r.max) return r.color;
  return "#67001f";
}

function radiusFor(n) {
  return Math.max(4, Math.min(22, Math.sqrt(n) * 0.9));
}

const escapeHtml = (s) => {
  const div = document.createElement("div");
  div.textContent = String(s ?? "");
  return div.innerHTML;
};

function fmtDate(iso) {
  const [y, m, d] = iso.split("-");
  const months = ["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"];
  return `${parseInt(d, 10)} ${months[parseInt(m, 10) - 1]} ${y}`;
}

function popupHtml(inc) {
  const rows = [
    ["Tanggal",        fmtDate(inc.d)],
    ["Provinsi",       inc.prov],
    ["Kabupaten/Kota", inc.kab],
    ["Tempat",         inc.loc],
    ["Bergejala",      `${inc.n.toLocaleString("id-ID")} orang`],
  ];
  if (inc.dead) rows.push(["Meninggal", `${inc.dead}`]);
  return `<div style="font-size:12px;line-height:1.45;max-width:280px">${
    rows.map(([k, v]) =>
      `<div><strong>${escapeHtml(k)}:</strong> ${escapeHtml(v)}</div>`,
    ).join("")
  }</div>`;
}

function tooltipHtml(inc) {
  return `<strong>${escapeHtml(fmtDate(inc.d))}</strong><br/>${
    escapeHtml(inc.kab)} — ${inc.n.toLocaleString("id-ID")} orang`;
}

async function buildMbg(_key, url) {
  const r = await fetch(url, { cache: "no-store" });
  if (!r.ok) throw new Error(`HTTP ${r.status} for MBG incidents`);
  const j = await r.json();
  // Chronological order so the earliest cases render underneath the latest.
  const incidents = [...(j.incidents || [])].sort((a, b) => a.d.localeCompare(b.d));

  const group = L.layerGroup();
  for (const inc of incidents) {
    if (typeof inc.lat !== "number" || typeof inc.lng !== "number") continue;
    L.circleMarker([inc.lat, inc.lng], {
      radius: radiusFor(inc.n),
      fillColor: colorFor(inc.n),
      fillOpacity: 0.8,
      color: "#fff",
      weight: 1.2,
      opacity: 0.9,
    })
      .bindTooltip(tooltipHtml(inc), { direction: "top", opacity: 0.95, sticky: true })
      .bindPopup(popupHtml(inc), { maxWidth: 320 })
      .addTo(group);
  }
  group._meta = {
    total:     j.total_incidents,
    first:     j.first_date,
    last:      j.last_date,
    bergejala: j.total_bergejala,
    meninggal: j.total_meninggal,
  };
  return group;
}

export const MBG_BUILDERS = new Map([["mbg", buildMbg]]);
