import L from "leaflet";

// Static GeoJSON generated by scripts/refresh-mbg.py — one polygon per
// affected kabupaten/kota, with aggregated victim counts in the properties.
function mbgUrl() {
  return `${import.meta.env.BASE_URL}mbg/incidents.geojson`;
}

export const MBG_SOURCES = [
  { key: "mbg_keracunan", label: "Keracunan MBG", group: "Insiden · MBG",
    kind: "mbg", url: mbgUrl() },
];

// Warm choropleth ramp. Buckets picked from the actual distribution (see
// scripts/refresh-mbg.py output): most kabupaten sit under 200 victims,
// but the tail runs into the thousands, so give the top few their own bins
// or they all read as the same color.
const RAMP = [
  { max: 50,       color: "#fee8c8", label: "≤ 50" },
  { max: 200,      color: "#fdbb84", label: "51–200" },
  { max: 500,      color: "#fc8d59", label: "201–500" },
  { max: 1000,     color: "#e34a33", label: "501–1.000" },
  { max: 2000,     color: "#b30000", label: "1.001–2.000" },
  { max: Infinity, color: "#7f0000", label: "> 2.000" },
];

export const MBG_RAMP = RAMP;

function colorFor(n) {
  for (const r of RAMP) if (n <= r.max) return r.color;
  return "#7f0000";
}

const BASE_STYLE = {
  weight: 0.6,
  color: "#ffffff",
  opacity: 0.9,
  fillOpacity: 0.72,
};
const HOVER_STYLE = {
  weight: 2,
  color: "#1a1614",
  opacity: 1,
  fillOpacity: 0.85,
};

const escapeHtml = (s) => {
  const div = document.createElement("div");
  div.textContent = String(s ?? "");
  return div.innerHTML;
};

function fmtDate(iso) {
  const [y, m, d] = iso.split("-");
  const months = ["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"];
  return `${parseInt(d, 10)} ${months[parseInt(m, 10) - 1]} ${y}`;
}

function popupHtml(p) {
  const rows = [
    ["Kabupaten/Kota", p.kab],
    ["Provinsi",       p.prov],
    ["Kejadian",       `${p.kj} insiden`],
    ["Bergejala",      `${p.n.toLocaleString("id-ID")} orang`],
  ];
  if (p.dd) rows.push(["Meninggal", `${p.dd}`]);
  const rowsHtml = rows.map(([k, v]) =>
    `<div><strong>${escapeHtml(k)}:</strong> ${escapeHtml(v)}</div>`,
  ).join("");

  const top = (p.top || []).slice(0, 3);
  const topHtml = top.length
    ? `<div style="margin-top:8px;padding-top:6px;border-top:1px solid rgba(0,0,0,.12)">
         <div style="font-size:11px;letter-spacing:.06em;text-transform:uppercase;opacity:.7;margin-bottom:4px">Insiden terbesar</div>
         ${top.map(t =>
           `<div style="display:flex;justify-content:space-between;gap:8px;margin-bottom:2px">
              <span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHtml(t.loc)}
                <span style="opacity:.6;font-size:11px">· ${escapeHtml(fmtDate(t.d))}</span>
              </span>
              <span style="font-weight:600;white-space:nowrap">${t.n.toLocaleString("id-ID")}</span>
            </div>`,
         ).join("")}
       </div>`
    : "";

  return `<div style="font-size:12px;line-height:1.5;max-width:300px">${rowsHtml}${topHtml}</div>`;
}

function tooltipHtml(p) {
  return `<strong>${escapeHtml(p.kab)}</strong>
    <span style="opacity:.7">— ${escapeHtml(p.prov)}</span><br/>
    ${p.n.toLocaleString("id-ID")} orang bergejala · ${p.kj} kejadian`;
}

function styleFor(feature) {
  return { ...BASE_STYLE, fillColor: colorFor(feature.properties.n) };
}

async function buildMbg(_key, url) {
  const r = await fetch(url, { cache: "no-store" });
  if (!r.ok) throw new Error(`HTTP ${r.status} for MBG GeoJSON`);
  const fc = await r.json();

  const layer = L.geoJSON(fc, {
    style: styleFor,
    onEachFeature: (feature, sub) => {
      const p = feature.properties;
      sub.bindTooltip(tooltipHtml(p), { sticky: true, direction: "top", opacity: 0.95 });
      sub.bindPopup(popupHtml(p), { maxWidth: 340 });
      sub.on({
        mouseover: (e) => e.target.setStyle(HOVER_STYLE),
        mouseout:  (e) => layer.resetStyle(e.target),
      });
    },
  });
  layer._meta = {
    total:     fc.total_incidents,
    kabkota:   fc.features.length,
    first:     fc.first_date,
    last:      fc.last_date,
    bergejala: fc.total_bergejala,
    meninggal: fc.total_meninggal,
  };
  return layer;
}

export const MBG_BUILDERS = new Map([["mbg", buildMbg]]);
